#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl2,  solenoid1,      sensorDigitalOut)
#pragma config(Sensor, I2C_1,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port4,           MiddleMotor,   tmotorVex393, openLoop)
#pragma config(Motor,  port5,           TowerLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port6,           TowerRight,    tmotorVex393, openLoop)
#pragma config(Motor,  port7,           ClawMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port8,           LauncherMotor, tmotorVex393, openLoop)
#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	wait1Msec(2000);

	nMotorEncoder[RightMotor] = 0;
	nMotorEncoder[LeftMotor] = 0;

	while(nMotorEncoder[RightMotor] < 1000)
	{
		//Move forward at half power
		motor[RightMotor] = 127;
		motor[LeftMotor]	= 49;
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

//============================================| TASK WHEELS |============================================
task Wheels()
{
  while(1 == 1)
  {
  	motor[MiddleMotor] = vexRT[Ch1];
    motor[RightMotor] = vexRT[Ch2];
    motor[LeftMotor]  = vexRT[Ch3];
    motor[MiddleMotor] = vexRT[Ch4];
  }
}

//====================================================================================================

//============================================| TASK CATAPULT |============================================
task Catapult()
{
	while(true)
	{
		if(vexRT[Btn6U] == 1 && vexRT[Btn6D] == 0)
		{
			motor[TowerLeft] = 500;
			motor[TowerRight] = 500;
		}
		else if(vexRT[Btn6U] == 0 && vexRT[Btn6D] == 1)
		{
			motor[TowerLeft] = -500;
			motor[TowerRight] = -500;
		}
		else if(vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0)
		{
			motor[TowerLeft] = 0;
			motor[TowerRight] = 0;
		}
	}
}
//====================================================================================================

//============================================| TASK LAUNCHER |==========================================
task Launcher()
{
	while(true)
	{
		if(vexRT[Btn5U] == 1 && vexRT[Btn5D] == 0)
		{
			motor[LauncherMotor] = 500;
		}
		else if(vexRT[Btn5U] == 0 && vexRT[Btn5D] == 1)
		{
			motor[LauncherMotor] = -500;
		}
		else if(vexRT[Btn5U] == 0 && vexRT[Btn5D] == 0)
		{
			motor[LauncherMotor] = 0;
		}
	}
}

//====================================================================================================

//============================================| TASK CLAW |==========================================
task Claw()
{
	while(true)
	{
		if(vexRT[Btn7U] == 1)
		{
			motor[ClawMotor] = 500;
		}
		else if(vexRT[Btn7U] == 0)
		{
			motor[ClawMotor] = -500;
		}
		else if(vexRT[Btn7U] == 0)
		{
			motor[ClawMotor] = 0;
		}
	}
}
//====================================================================================================

//============================================| TASK AUTONOMOUS |==========================================
task Autonomous()
{
	while(true)
	  {
//       go f*** yourself, <3 me
		}
}

//====================================================================================================

//============================================| TASK PNEUMATICS |==========================================
task Pneumatics()
{
  while(true)
  {
    if(vexRT[Btn8D] == 1)
    {
      SensorValue[solenoid1] = 1;
    }
    else
    {
      SensorValue[solenoid1] = 0;
    }
  }
}
//====================================================================================================

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task usercontrol()
{
  StartTask(Wheels);
  StartTask(Catapult);
  StartTask(Launcher);
  StartTask(Claw);
  StartTask(Autonomous);
  StartTask(Pneumatics);
  while(true)
  {     {
  }     }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
