#pragma config(Sensor, dgtl5,  solenoid1,      sensorDigitalOut)
#pragma config(Sensor, dgtl6,  solenoid2,      sensorDigitalOut)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           TowerLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           TowerRight,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!



/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	wait10Msec(100);
 	motor[RightMotor] = 127;
 	motor[LeftMotor] = 127;
 	wait1Msec(10000);
 	motor[RightMotor] = 0;
 	motor[LeftMotor] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

//============================================| TASK WHEELS |============================================
task Wheels()
{
  while(1 == 1)
  {
    motor[RightMotor] = vexRT[Ch2];
    motor[LeftMotor]  = vexRT[Ch3];
    }
}
//====================================================================================================

//============================================| TASK CATAPULT |============================================
task Catapult()
{
	while(true)
	{
		if(vexRT[Btn6U] == 1 && vexRT[Btn6D] == 0)
		{
			motor[TowerLeft] = 127;
			motor[TowerRight] = 127;
		}
		else if(vexRT[Btn6U] == 0 && vexRT[Btn6D] == 1)
		{
			motor[TowerLeft] = -127;
			motor[TowerRight] = -127;
		}
		else if(vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0)
		{
			motor[TowerLeft] = 0;
			motor[TowerRight] = 0;
		}
	}
}
//====================================================================================================

//============================================| TASK PNEUMATICS |==========================================
task Pneumatics()
{
  while(true)
  {
    if(vexRT[Btn5U] == 1)
    {
      SensorValue[solenoid1] = 1;
      SensorValue[solenoid2] = 1;
    }
    else
    {
      SensorValue[solenoid1] = 0;
      SensorValue[solenoid2] = 0;
    }
  }
}
//====================================================================================================

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task usercontrol()
{
  StartTask(Wheels);
  StartTask(Catapult);
  StartTask(Pneumatics);
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
